# Generated by Django 4.0.1 on 2022-02-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_postmodel_order_postmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='order',
        ),
    ]
